/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.cidco.lwjgl;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.util.logging.Logger;
import javax.swing.JPanel;
import org.lwjgl.opengl.awt.GLData;

/**
 *
 * @author Maxime Lajoie
 */
public class LWJGLPanel extends JPanel {

    private LWJGLCanvas canvas;
    private GLData data;
   
    static final Logger LOG = Logger.getLogger(LWJGLPanel.class.getName());
    
    public LWJGLPanel() {
        initComponents(); 
        
        setLayout(new BorderLayout());
        
        setDoubleBuffered(true);
        
        setMinimumSize(new Dimension(0, 0));
        data = new GLData();
        data.samples = 4;
        canvas = new LWJGLCanvas(data);
        add(canvas, BorderLayout.CENTER);
    }
    
    public LWJGLCanvas getCanvas(){
        return canvas;
    }
    
    public void render(){
        canvas.render();
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(null);
        setForeground(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
